notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
install: true
dist: xenial
python: 3
addons:
  apt:
    update: true
    packages:
      - jq
      - zip
      - curl
      - bash
      - unzip
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
  - pip install --user $(whoami) --upgrade httpie >/dev/null 2>&1
  - http --version --debug
  #
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 5432 5672 27017 8080 8000 8081 80 80
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: Maven tests (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -U >/dev/null
        - java -jar $TRAVIS_BUILD_DIR/target/*-SNAPSHOT.jar &
        - wait_for 8080
        - http :8080/
        - sleep 3s
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: Maven tests (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -U >/dev/null
        - java -jar $TRAVIS_BUILD_DIR/target/*-SNAPSHOT.jar &
        - wait_for 8080
        - http :8080/
        - sleep 3s
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: Maven updates (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U
    - stage: test
      jdk: openjdk11
      name: Maven updates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U
cache:
  directories:
    - ~/.m2
  packages: true
  pip: true
